---
# Sample Playbook to install MySQL & use "mysql_secure_installation" Ansible Module

- name: Install & Secure MySQL
  hosts: localhost, ubuntu
  become: true
  tasks:
    - name: Install Mariadb
      apt:
        name:
          - mariadb-server
          - python-dev
          - libmysqlclient-dev
        state: latest
      when: ansible_os_family == 'Debian'

    - name: Start Mysql Service
      service:
        name: mysql
        state: started
        enabled: true
      when: ansible_os_family == 'Debian'

    - name: Install Mariadb
      yum:
        name:
          - mariadb-server
          - mariadb
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Start Mariadb Service
      service:
        name: mariadb
        state: started
        enabled: true
      when: ansible_os_family == 'RedHat'

    - name: pip
      package:
        name: python-pip
        state: latest

    - name: Install the Python MySQLB module
      pip: name=MySQL-python

    - name: test mysql_secure_installation
      mysql_secure_installation:
        login_password: ''
        new_password: password22
        user: root
        login_host: localhost
        hosts: ['localhost', '127.0.0.1', '::1']
        change_root_password: true
        remove_anonymous_user: true
        disallow_root_login_remotely: true
        remove_test_db: true
      register: secure

    - debug:
        var: secure

